language: php

php:
- '7.2'

services:
- mysql

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS `test` CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci";'

install:
- printf "\n\n\n\n\nyes\n\n" | pecl install swoole
- composer install

script:
- ./vendor/bin/phpunit tests --repeat 100
- php tests/cluster.php
