language: php

php:
- '7.2'
- '7.3'

services:
- mysql

dist: trusty
sudo: false

cache:
  directories:
  - ~/.composer
  - ~/.php-ext

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS `test` CHARACTER SET "utf8mb4" COLLATE "utf8mb4_general_ci";'
- mysql -e 'USE `test`;CREATE TABLE `items` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `key` char(32) NOT NULL, `val` char(128) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;'
- source <(curl -sL https://github.com/carno-php/travis-ci/raw/master/tests-prepare.sh)

install:
- composer update

script:
- testing

after_success:
- coveralls
